/*
      #################
      ##SCHEMA LOGICO##
      #################

      ATLETI(ID_A,Nome_A,Cognome_A,Data_N,Istituto,Nazionalita_A,ID_Sq)
      SQUADRE(ID_Sq,Nazionalita_Sq,Nome_Sq)
      GARE(ID_G,Nome_G,Tipologia,Punteggio_Max,ID_Se,ID_F)
      SEDI(ID_Se,Nome_Se,Citta,Nazione)
      FASI(ID_F,Nome_F)
      PARTECIPANO_A(ID_A,ID_G,Punteggio_A,Posizione_A)
      PARTECIPANO_S(ID_Sq,ID_G,Punteggio_Sq,Posizione_Sq)
*/

CREATE TABLE SQUADRE(
  ID_Sq CHAR(5) NOT NULL UNIQUE,
  Nazionalita_Sq VARCHAR(25) NOT NULL,
  Nome_Sq VARCHAR(25) NOT NULL,

  PRIMARY KEY(ID_Sq)
);

CREATE TABLE FASI(
  ID_F CHAR(5) NOT NULL UNIQUE,
  Nome_F VARCHAR(25) NOT NULL,

  PRIMARY KEY(Nome_F)
);

CREATE TABLE ATLETI(
  ID_A CHAR(5) NOT NULL UNIQUE,
  Nome_A VARCHAR(25) NOT NULL,
  Cognome_A VARCHAR(25) NOT NULL,
  Data_N DATE NOT NULL,
  Istituto VARCHAR(25),
  Nazionalità_A VARCHAR(25) NOT NULL,
  ID_Sq CHAR(5),

  PRIMARY KEY(ID_A),
  FOREIGN KEY (ID_Sq) REFERENCES SQUADRE(ID_Sq)

);

CREATE TABLE SEDI(
  ID_Se CHAR(5) NOT NULL UNIQUE,
  Nome_Se VARCHAR(25) NOT NULL,
  Citta VARCHAR(25) NOT NULL,
  Nazione VARCHAR(15) NOT NULL,

  PRIMARY KEY(ID_Se)

);

CREATE TABLE GARE(
  ID_G CHAR(5) NOT NULL UNIQUE,
  Nome_G VARCHAR(25) NOT NULL,
  Tipologia VARCHAR(25),
  Punteggio_Max INT(2),
  ID_Se CHAR(5) NOT NULL,
  ID_F  CHAR(5) NOT NULL,

  PRIMARY KEY(ID_G),
  FOREIGN KEY (ID_Se) REFERENCES SEDI(ID_Se),
  FOREIGN KEY (ID_F) REFERENCES FASI(ID_F)
);

CREATE TABLE PARTECIPANO_A(
  ID_A CHAR(5) NOT NULL,
  ID_G CHAR(5) NOT NULL,
  Punteggio_A INT(2),
  Posizione_A TINYINT,

  PRIMARY KEY(ID_A, ID_G),
  FOREIGN KEY (ID_A) REFERENCES ATLETI(ID_A),
  FOREIGN KEY (ID_G) REFERENCES GARE(ID_G)
);

CREATE TABLE PARTECIPANO_S(
  ID_Sq CHAR(5) NOT NULL,
  ID_G CHAR(5) NOT NULL,
  Punteggio_Sq INT(2) NOT NULL,
  Posizione_Sq TINYINT,

  PRIMARY KEY(ID_Sq, ID_G),
  FOREIGN KEY (ID_Sq) REFERENCES SQUADRE(ID_Sq),
  FOREIGN KEY (ID_G) REFERENCES GARE(ID_G)
);
